WPM_ENABLE = yes
CAPS_WORD_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
OLED_TIMEOUT = 120000
OLED_FADE_OUT = 15
OLED_BRIGHTNESS = 128

BACKLIGHT_ENABLE = no

